recipe: default.v1

language: en

pipeline:
  - name: SpacyNLP
    model: en_core_web_md
  - name: EntitySynonymMapper
  - name: SpacyTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
  - name: SpacyFeaturizer
#  - name: RegexFeaturizer
#  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
#  - name: CountVectorsFeaturizer
#    analyzer: "char_wb"
#    min_ngram: 1
#    max_ngram: 4
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: yes
  - name: ResponseSelector
    epochs: 50

policies:
  - name: TEDPolicy
    max_history: 7
    epochs: 10
    constrain_similarities: yes
  - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    epochs: 10
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'